MODEL:
  META_ARCHITECTURE: "TurboSeg"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  TRAIN_CLASS_JSON: "datasets/coco.json"
  TEST_CLASS_JSON: "datasets/coco.json"
  CLIP_PRETRAINED: "Convnext-B"
  CLIP_FINETUNE: "full"
  SEM_SEG_HEAD:
    NAME: "TurboSegHead"
    NUM_CLASSES: 171
    IGNORE_VALUE: 255
    TEXT_GUIDANCE_DIM: 640
    TEXT_GUIDANCE_PROJ_DIM: [128, 64]
    DECODER_DIMS: [64, 32]
    DECODER_GUIDANCE_DIMS: [512, 256]
    DECODER_GUIDANCE_PROJ_DIMS: [32, 16]
    HIDDEN_DIMS: 128
    NUM_PROMPTS: 1
  PROMPT_ENSEMBLE_TYPE: "single"
DATASETS:
  TRAIN: ("coco_2017_train_stuff_all_sem_seg",)
  TEST: ("coco_2017_test_stuff_all_sem_seg",)
INPUT:
  MIN_SIZE_TRAIN: (768, )
  MAX_SIZE_TRAIN: 2666
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 2560
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (768, 768)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0001
  MAX_ITER: 100
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  CLIP_MULTIPLIER: 0.01
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 2
VERSION: 2
CUDNN_BENCHMARK: True