_BASE_: config.yaml
MODEL:
  CLIP_PRETRAINED: "Convnext-L"
  SEM_SEG_HEAD:
    TEXT_GUIDANCE_DIM: 768
    TEXT_GUIDANCE_PROJ_DIM: [128, 128]
    DECODER_DIMS: [128, 64]
    DECODER_GUIDANCE_DIMS: [768, 384]
    DECODER_GUIDANCE_PROJ_DIMS: [64, 32]
  PROMPT_ENSEMBLE_TYPE: "single"
INPUT:
  MIN_SIZE_TRAIN: (640, )
  CROP:
    SIZE: (640, 640)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 5000
SEED: 37035241