_BASE_: config.yaml
MODEL:
  CLIP_PRETRAINED: "Convnext-B"
  SEM_SEG_HEAD:
    TEXT_GUIDANCE_DIM: 640
    TEXT_GUIDANCE_PROJ_DIM: [128, 64]
    DECODER_DIMS: [64, 32]
    DECODER_GUIDANCE_DIMS: [512, 256]
    DECODER_GUIDANCE_PROJ_DIMS: [32, 16]
  PROMPT_ENSEMBLE_TYPE: "single"
INPUT:
  MIN_SIZE_TRAIN: (768, )
  CROP:
    SIZE: (768, 768)
SOLVER:
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 5000
SEED: 37035241